---
version: '3.7'

services:
  db:
    image: mysql:5.7.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "${PORT_TESTING_WORDPRESS:-8000}:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdb
    volumes: ["./html:/var/www/html"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8282:80
    environment:
      MYSQL_USER: root
volumes:
  wordpress:
  db: